### ISSUE TITLE
surprise data includes solutions files

### ISSUE THREAD

**Issue by ckirov** [sigtyp/ST2022#22]
Is it an error for the solution files to be included with the final test sets for the surprise data, as they currently are? Should we ignore those files when preparing submissions? Thanks!

**Comment by LinguList** [comment]
Good point. I did not really think about this so far. I think I had a less strict understanding of how such a task goes. But sure: ideally, we'd have not shared solutions, but held the data out, only providing training sets, etc. 

However, there is a problem with the way in which we generate the data for testing: we drop one word per language and iterate over all languages. As a result, even from looking at the test-file, you have solutions for the other data (even cognate set identifiers mark this). AND we have the original data and a transparent process by which we generate the held-out data for testing, so if one wants to see the solutions, one can easily generate them from what we have out there anyway.

I'd therefore say: since we assume that all systems will be openly shared, and that the way in which systems were trained follows our rules (only the train-files are allowed to train the data), there's not much space for cheating with the solutions files, and those who have created their system can just use the methods we provide to test how well they perform and also prepare this for their report.

We'll ask all systems to be shared openly, in replicable code, and we'll ask for all detailed results which we'll upload here, so I think this should be fine, and I'd say people are explicitly allowed to check the results with the solutions files, while I assume that any kind of fine-tuning parameters to get best results on the ten surprise datasets should be avoided.

**Comment by ckirov** [comment]
Got it, we'll just make sure to avoid including the test data and solutions in any tuning.

**Comment by LinguList** [comment]
Yep. And we'll try to double-check all systems later, once they are submitted, to make sure they can be applied later, and that the correct files are used for training.
